name: Send Dispatch

on:
  push:
    branches:
    - master

jobs:
  dispatch:
    if: github.repository_owner == 'mmcesim'
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT }}
        repository: mmcesim/mmcesim-doxygen
        event-type: mmcesim-cli-push
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
