name: Check and Apply Clang-Format

on: [push]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Clang Format
        run: chmod +x ./misc/format && ./misc/format
      - name: Commit Files
        run: |
          git config --local user.email "bot@mmcesim.org"
          git config --local user.name "mmcesim-bot"
          git commit -am"Apply Clang-Format" || echo "Clang-Format already satisfied."
      - name: Push Changes
        uses: ad-m/github-push-action@master
